/** \brief FUNCION QUE MUESTRA EL MENU DE OPCIONES
 * \param PIDE AL USUARIO ELEGIR UNA OPCION PARA REALIZAR UNA OPERACION
 * \return
 */
void menu(void);

/** \brief FUNCION QUE REALIZA LA OPERACION SUMA
 * \param PIDE AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS
 * \return DEVUELVE LA SUMA DE LA OPERACION
 */
float sumar(float,float);

/** \brief FUNCION QUE REALIZA LA OPERACION RESTA
 * \param PIDE AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS
 * \return DEVUELVE LA RESTA DE LA OPERACION
 */
float restar(float,float);

/** \brief FUNCION QUE REALIZA LA OPERACION MULTIPLICAR
 * \param PIDE AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS
 * \return DEVUELVE LA MULTIPLICACION DE LA OPERACION
 */
float multiplicar(float,float);

/** \brief FUNCION QUE REALIZA LA OPERACION DIVIDIR
 * \param PIDE AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS
 * \return DEVUELVE LA DIVISION DE LA OPERACION
 */
float dividir(float,float);

/** \brief FUNCION QUE REALIZA LA OPERACION FACTORIAL DEL PRIMER OPERANDO
 * \param PIDE AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS
 * \return DEVUELVE LA FACTORIZACION DEL PRIMER OPERANDO
 */
long factorizar(float);

/** \brief FUNCION QUE REALIZA LA OPERACION FACTORIAL DEL PRIMER OPERANDO
 * \param PIDE AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS
 * \return DEVUELVE LA FACTORIZACION DEL SEGUNDO OPERANDO
 */
long factorizar2(float);

